version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gsh
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.BUILD_VERSION={{.Version}}

source:
  enabled: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

# NFPM for .deb and .rpm packages
nfpms:
  - id: packages
    package_name: gsh
    vendor: robottwo
    homepage: https://github.com/robottwo/gsh_prime
    maintainer: robottwo <robottwo@users.noreply.github.com>
    description: A modern, POSIX-compatible, generative shell
    license: GPL-3.0-or-later
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: shells
    priority: optional
    rpm:
      group: System Environment/Shells
      compression: xz
    deb:
      lintian_overrides:
        - statically-linked-binary
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/gsh/LICENSE
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/gsh/README.md
        file_info:
          mode: 0644

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew Casks (replaces deprecated brews section as of GoReleaser v2.10)
homebrew_casks:
  - name: gsh
    homepage: https://github.com/robottwo/gsh_prime
    description: A modern, POSIX-compatible, generative shell
    license: GPL-3.0-or-later
    commit_author:
      name: robottwo
      email: robottwo@users.noreply.github.com
    repository:
      owner: robottwo
      name: homebrew-gsh
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

# Scoop (Windows)
scoops:
  - name: gsh
    homepage: https://github.com/robottwo/gsh_prime
    description: A modern, POSIX-compatible, generative shell
    license: GPL-3.0-or-later
    repository:
      owner: robottwo
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"

# AUR binary package
aurs:
  - name: gsh-bin
    homepage: https://github.com/robottwo/gsh_prime
    description: A modern, POSIX-compatible, generative shell
    license: GPL-3.0-or-later
    maintainers:
      - "robottwo <robottwo@users.noreply.github.com>"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gsh-bin.git"
    commit_author:
      name: robottwo
      email: robottwo@users.noreply.github.com
    package: |-
      # bin
      install -Dm755 "./gsh" "${pkgdir}/usr/bin/gsh"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gsh/LICENSE"

# AUR source package
aur_sources:
  - name: gsh
    homepage: https://github.com/robottwo/gsh_prime
    description: A modern, POSIX-compatible, generative shell
    license: GPL-3.0-or-later
    maintainers:
      - "robottwo <robottwo@users.noreply.github.com>"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gsh.git"
    commit_author:
      name: robottwo
      email: robottwo@users.noreply.github.com
    prepare: |-
      cd "${srcdir}/${_pkgsrc}"
      go mod download
    build: |-
      cd "${srcdir}/${_pkgsrc}"
      export CGO_ENABLED=0
      export GOFLAGS="-trimpath -mod=readonly -modcacherw"
      go build -ldflags="-X main.BUILD_VERSION=${pkgver}" -o "./bin/${pkgname}" "./cmd/${pkgname}"
    package: |-
      cd "${srcdir}/${_pkgsrc}"

      # bin
      install -Dsm755 "./bin/${pkgname}" "${pkgdir}/usr/bin/${pkgname}"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

      # information
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/${pkgname}/README.md"
      install -Dm644 "./ROADMAP.md" "${pkgdir}/usr/share/doc/${pkgname}/ROADMAP.md"
      install -Dm644 "./CHANGELOG.md" "${pkgdir}/usr/share/doc/${pkgname}/CHANGELOG.md"
