# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bish < Formula
  desc "A modern, POSIX-compatible, generative shell"
  homepage "https://github.com/robottwo/bishop"
  version "0.22.2"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robottwo/bishop/releases/download/v0.22.2/bish_Darwin_x86_64.tar.gz"
      sha256 "2f83a816e321c76f7988ced73624b3b860e16975c4f81f1acdd9287b0fb78a71"

      def install
        bin.install "bish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robottwo/bishop/releases/download/v0.22.2/bish_Darwin_arm64.tar.gz"
      sha256 "fdb4f19d958642193bedb4f54f25f77e8a05f4274343fa9344f2f928727073e3"

      def install
        bin.install "bish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robottwo/bishop/releases/download/v0.22.2/bish_Linux_x86_64.tar.gz"
        sha256 "9a8abce8987449c5933dacb147541d1175edbdaa38b1726085d1c18ce9d4c6ad"

        def install
          bin.install "bish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robottwo/bishop/releases/download/v0.22.2/bish_Linux_arm64.tar.gz"
        sha256 "258da8336167a66888dba9b4f78d8c57bce0d112bde7ddc7757cbab5efbd2441"

        def install
          bin.install "bish"
        end
      end
    end
  end
end
